import type { Property, Testimonial, TeamMember, BlogPost, FaqItem } from './types';

export const properties: Property[] = [
  {
    id: 'modern-villa-sunset-heights',
    title: 'Modern Villa in Sunset Heights',
    price: 2800000,
    location: 'Beverly Hills, CA',
    type: 'Villa',
    beds: 5,
    baths: 6,
    area: 6500,
    description: 'An architectural masterpiece offering breathtaking views and unparalleled luxury. This modern villa features an open-plan living space, an infinity pool, and state-of-the-art amenities, perfect for those who demand the very best.',
    features: ['Infinity Pool', 'Home Theater', 'Gourmet Kitchen', '3-Car Garage', 'Ocean View', 'Smart Home System'],
    imageIds: ['property-1-ext', 'property-1-int', 'property-1-kit'],
    isFeatured: true,
  },
  {
    id: 'luxury-city-apartment',
    title: 'Luxury City Apartment',
    price: 1500000,
    location: 'Manhattan, NY',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    area: 2400,
    description: 'A stunning apartment in the heart of the city, offering panoramic skyline views. With floor-to-ceiling windows, high-end finishes, and access to exclusive building amenities, this property is the epitome of urban luxury.',
    features: ['24/7 Concierge', 'Rooftop Terrace', 'Fitness Center', 'Valet Parking', 'City Views'],
    imageIds: ['property-2-ext', 'property-2-int'],
    isFeatured: true,
  },
  {
    id: 'charming-family-house',
    title: 'Charming Family House',
    price: 850000,
    location: 'Greenwich, CT',
    type: 'House',
    beds: 4,
    baths: 3,
    area: 3200,
    description: 'Nestled in a quiet, family-friendly neighborhood, this charming house boasts a spacious backyard, a newly renovated kitchen, and a cozy fireplace. It\'s the perfect place to create lasting memories with your loved ones.',
    features: ['Large Backyard', 'Renovated Kitchen', 'Fireplace', 'Two-Car Garage', 'Good School District'],
    imageIds: ['property-3-ext'],
    isFeatured: true,
  },
  {
    id: 'exclusive-penthouse-suite',
    title: 'Exclusive Penthouse Suite',
    price: 4200000,
    location: 'Miami, FL',
    type: 'Penthouse',
    beds: 4,
    baths: 5,
    area: 5000,
    description: 'This exclusive penthouse offers the ultimate in luxury living, with a private rooftop pool and expansive terrace. Enjoy 360-degree views of the ocean and city from this one-of-a-kind property.',
    features: ['Private Rooftop Pool', 'Expansive Terrace', '360-Degree Views', 'Private Elevator', 'Wine Cellar'],
    imageIds: ['property-4-ext'],
    isFeatured: false,
  },
  {
    id: 'beachfront-escape',
    title: 'Beachfront Escape',
    price: 3100000,
    location: 'Malibu, CA',
    type: 'House',
    beds: 3,
    baths: 4,
    area: 3500,
    description: 'Wake up to the sound of waves in this beautiful beachfront home. Featuring direct beach access, an open-concept living area, and large decks for entertaining, this is coastal living at its finest.',
    features: ['Direct Beach Access', 'Oceanfront Deck', 'Modern Design', 'Sunset Views', 'Gated Community'],
    imageIds: ['property-5-ext'],
    isFeatured: false,

  },
  {
    id: 'cozy-country-cottage',
    title: 'Cozy Country Cottage',
    price: 650000,
    location: 'The Cotswolds, UK',
    type: 'Cottage',
    beds: 2,
    baths: 2,
    area: 1800,
    description: 'A picture-perfect cottage surrounded by lush gardens. This cozy retreat features original stone walls, a wood-burning stove, and a tranquil atmosphere, perfect for a peaceful country life.',
    features: ['Lush Gardens', 'Wood-Burning Stove', 'Original Features', 'Quiet Location', 'Country Views'],
    imageIds: ['property-6-ext'],
    isFeatured: false,
  },
];

export const featuredProperties = properties.filter(p => p.isFeatured);

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: 'The Johnson Family',
    location: 'New York, NY',
    rating: 5,
    quote: 'Property Evangelist found us our dream home. The service was impeccable, and their attention to detail was second to none. We couldn\'t be happier!',
    imageId: 'testimonial-1',
  },
  {
    id: 2,
    name: 'Chen Wei',
    location: 'Singapore',
    rating: 5,
    quote: 'As an expat, finding a home in a new country was daunting. Their team made the process seamless and stress-free. Truly a golden standard of service.',
    imageId: 'testimonial-3',
  },
  {
    id: 3,
    name: 'David & Emily Carter',
    location: 'Los Angeles, CA',
    rating: 5,
    quote: 'From the first meeting to closing, the experience was luxurious and professional. They understood our needs for comfort and exclusivity perfectly.',
    imageId: 'testimonial-2',
  },
   {
    id: 4,
    name: 'Sophia Rodriguez',
    location: 'Miami, FL',
    rating: 5,
    quote: 'The team\'s knowledge of the luxury market is incredible. They helped me find a penthouse with the exact features I wanted. Highly recommended!',
    imageId: 'testimonial-1',
  },
];

export const team: TeamMember[] = [
    {
        id: 1,
        name: 'Eleonora Vance',
        role: 'Founder & Lead Realtor',
        bio: 'With over 15 years of experience in luxury real estate, Eleonora founded Property Evangelist to bring a new level of integrity and personalized service to the market. Her passion is turning clients\' dreams into reality.',
        imageId: 'team-1',
    },
    {
        id: 2,
        name: 'James Peterson',
        role: 'Senior Property Advisor',
        bio: 'James specializes in international clients and high-value estates. His market expertise and sharp negotiation skills ensure every client gets the best possible outcome.',
        imageId: 'team-2',
    },
    {
        id: 3,
        name: 'Chloe Dubois',
        role: 'Client Relations Manager',
        bio: 'Chloe is the heart of our client experience. She ensures every interaction is smooth, pleasant, and meets our golden standard of service, from the first call to beyond the closing date.',
        imageId: 'team-3',
    },
]

export const blogPosts: BlogPost[] = [
    {
        slug: 'top-5-features-of-a-luxury-home-in-2024',
        title: 'Top 5 Features of a Luxury Home in 2024',
        excerpt: 'From smart home integration to sustainable materials, discover what defines a luxury home in the modern era.',
        date: '2024-07-15',
        author: 'Eleonora Vance',
        content: 'The concept of luxury is always evolving. In 2024, it\'s about more than just square footage or a prestigious address. Today\'s high-end buyers are looking for a blend of technology, sustainability, and wellness. Here are the top 5 features defining a luxury home this year: \n\n1. **Smart Home Integration:** Seamless control over lighting, climate, security, and entertainment is no longer a perk—it\'s a requirement. \n2. **Wellness-Oriented Amenities:** Think home gyms with virtual trainers, spa-like bathrooms with saunas, and air/water purification systems. \n3. **Sustainable & Eco-Friendly Design:** Buyers are increasingly conscious of their environmental impact. Solar panels, geothermal heating, and recycled materials are major selling points. \n4. **Indoor-Outdoor Living:** Disappearing glass walls, outdoor kitchens, and beautifully landscaped living spaces blur the lines between inside and out. \n5. **Ultimate Privacy & Security:** In an increasingly connected world, true luxury is the ability to disconnect. Gated properties, advanced security systems, and natural privacy screens are paramount.',
        imageId: 'blog-2',
        isPopular: true,
    },
    {
        slug: 'navigating-the-market-a-guide-for-first-time-buyers',
        title: 'Navigating the Market: A Guide for First-Time Buyers',
        excerpt: 'Buying your first home can be overwhelming. Our guide breaks down the process into simple, manageable steps.',
        date: '2024-06-28',
        author: 'James Peterson',
        content: 'Buying your first home is one of life\'s most exciting milestones, but it can also feel complex. Here\'s a simplified guide to help you navigate the journey: \n\n1. **Get Pre-Approved:** Before you start house hunting, know your budget. A mortgage pre-approval shows sellers you\'re a serious buyer. \n2. **Define Your Needs vs. Wants:** Make a list of your must-haves (e.g., number of bedrooms, location) and your nice-to-haves (e.g., a home office, a backyard). \n3. **Find the Right Realtor:** A good agent is your most valuable asset. They provide market expertise, negotiation skills, and guidance. (Hint: You\'re in the right place!) \n4. **The Search & Offer:** Your agent will help you find properties and make a competitive offer. \n5. **Inspection & Closing:** Once your offer is accepted, you\'ll conduct a home inspection. If all goes well, you\'ll proceed to closing and get the keys to your new home!',
        imageId: 'blog-1',
        isPopular: true,
    },
    {
        slug: 'investment-properties-what-to-look-for',
        title: 'Investment Properties: What to Look For',
        excerpt: 'Learn the key factors to consider when purchasing a property for investment to maximize your return.',
        date: '2024-05-19',
        author: 'Eleonora Vance',
        content: 'Real estate can be a powerful investment, but not all properties are created equal. When evaluating an investment property, focus on these key factors: \n\n- **Location:** Look for areas with strong job growth, good schools, and low crime rates. Proximity to amenities is a huge plus. \n- **Cash Flow:** This is the money left over after all expenses are paid. A positive cash flow is essential for a successful rental property. \n- **Appreciation Potential:** Research the area\'s development plans. New infrastructure or businesses can significantly increase property values over time. \n- **Property Condition:** A property that needs significant repairs can eat into your profits. Get a thorough inspection to understand the true cost of ownership.',
        imageId: 'blog-3',
    },
];

export const faqs: FaqItem[] = [
    {
        id: 'faq1',
        question: 'What is the first step in the home buying process?',
        answer: 'The first step is to get pre-approved for a mortgage. This will give you a clear understanding of your budget and show sellers that you are a serious buyer. We can connect you with trusted financial partners to help you get started.',
    },
    {
        id: 'faq2',
        question: 'How do you determine the value of a property?',
        answer: 'We conduct a Comparative Market Analysis (CMA), which involves evaluating recently sold properties with similar features in the same area. We also consider current market trends, property condition, and unique features to determine the most accurate and competitive price.',
    },
    {
        id: 'faq3',
        question: 'What services do you offer for international clients?',
        answer: 'We offer a comprehensive suite of services for international expatriates, including virtual tours, assistance with legal and financial paperwork, neighborhood guides, and relocation support. Our goal is to make your transition as smooth and seamless as possible.',
    },
    {
        id: 'faq4',
        question: 'How long does the closing process typically take?',
        answer: 'The closing process can vary, but it typically takes between 30 to 60 days from the time your offer is accepted. This period allows for mortgage processing, appraisals, title searches, and home inspections.',
    },
    {
        id: 'faq5',
        question: 'What is the "golden standard of service"?',
        answer: 'Our "golden standard of service" is our commitment to providing an exceptional experience guided by integrity, innovation, and proactive communication. We anticipate your needs and go above and beyond to ensure your complete satisfaction throughout your real estate journey.',
    },
];
